export type ClientMessage = RegMessage | CreateRoomMessage | AddUserToRoomMessage;

export type RouterMessage = {
  response: ResponseDto,
  recipients: string[] | 'all',
  registerUserId?: string
}

export type ResponseDto = {
  type: CommandType,
  data: UserAccountResponseDto | Room[] | Winner[] | Game,
  id: number
};

interface BaseMessage<T extends CommandType, D> {
  type: T;
  data: D;
  id: number;
}

export const Command = {
  REG: 'reg',
  CREATE_ROOM: 'create_room',
  UPDATE_ROOM: 'update_room',
  UPDATE_WINNERS: 'update_winners',
  ADD_USER_TO_ROOM: 'add_user_to_room', 
  CREATE_GAME: 'create_game'
} as const;

type CommandType = typeof Command[keyof typeof Command];

type RegMessage = BaseMessage<'reg', UserAccount>;
type CreateRoomMessage = BaseMessage<'create_room', string>;
type AddUserToRoomMessage = BaseMessage<'add_user_to_room', { indexRoom: string }>

export type UserAccount = { name: string; password: string, id: string };
export type UserAccountResponseDto = {
  name: string,
  index: string,
  error: boolean,
  errorText: string,
};

export type RoomUser = {
  name: string;
  index: string;
}

export type Room = {
  roomId: string;
  roomUsers: RoomUser[]
}

export type Winner = {
  userId: string;
  name: string;
  wins: number;
}

export type Game = {
  idGame: string,  
  idPlayer: string, /* generated by server id for player in the game session, not enemy (unique id for every player) */
}
